<a href="https://colab.research.google.com/github/RVsilva21/Elimina-o-de-Gauss---RV/blob/main/LU_Gauss.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

A = np.array([
    [1, 6, 2, 4],
    [3, 19, 4, 15],
    [1, 4, 8, -12],
    [5, 33, 9, 3],
])

B = np.array([
    [8],
    [25],
    [18],
    [25],
])

A = np.concatenate((A, B), axis=1)

pivo = A[0,0]
fator = A[1,0]/pivo
A[1,:] = A[1,:] - fator*A[0,:]

fator = A[2,0]/pivo
A[2,:] = A[2,:] - fator*A[0,:]

fator = A[3,0]/pivo
A[3,:] = A[3,:] - fator*A[0,:]

pivo = A[1,1]
fator = A[2,1]/pivo

fator = A[2,1]/pivo
A[2,:] = A[2,:] - fator*A[1,:]

fator = A[3,1]/pivo
A[3,:] = A[3,:] - fator*A[1,:]

pivo = A[2,2]
fator = A[3,2]/pivo

fator = A[3,2]/pivo
A[3,:] = A[3,:] - fator*A[2,:]

print (A)



[[  1   6   2   4   8]
 [  0   1  -2   3   1]
 [  0   0   2 -10  12]
 [  0   0   0  -1 -48]]


In [ ]:
def substituicoes_sucessivas(A, b):

 n = len(A)
 x = n * [0]

 for i in range (0, n):
     S = 0
     for j in range (0, i):
         S = S + A[i][j] * x[j]
     x[i] = (b[i]-S)/A[i][i]

 return x

In [ ]:
from ast import Return
def identidade(n):
  m = []
  for i in range (0, n):
      linha = [0] * n
      linha[i] = 1
      m.append(linha)
  return m

In [ ]:
def lu(A):
  n = len(A)

  L = identidade(n)

  for k in range(0, n-1):
      for i in range(k+1, n):
          m = - A[i][k]/A[k][k]
          L[i][k] = -m

          for j in range (k+1, n):
              A[i][j] = m * A[k][j] + A[i][j]

          ## b[i] = m * b[k] + b[i]

          A[i][k] = 0

  return (L, A)

In [ ]:
def formata_matriz(M):
    m = len(M)
    n = len(M[0])
    s = ""

    for i in range(m):
        for j in range(n):
          s += "%9.3f" % M[i][j]
        s += "\n"
    return s

A = [[1, 6, 2, 4],
     [3, 19, 4, 15],
     [1, 4, 8, -12],
     [5, 33, 9, 3]
     ]

(L, U) = lu(A)

print("L: \n%s" % formata_matriz(L))
print("U: \n%s" % formata_matriz(U))

L: 
    1.000    0.000    0.000    0.000
    3.000    1.000    0.000    0.000
    1.000   -2.000    1.000    0.000
    5.000    3.000    2.500    1.000

U: 
    1.000    6.000    2.000    4.000
    0.000    1.000   -2.000    3.000
    0.000    0.000    2.000  -10.000
    0.000    0.000    0.000   -1.000

